import type { Analysis } from '../types'

export const MOCK_ANALYSIS: Analysis = {
  id: 'mock-uuid',
  symbol: 'BTC',
  tradingview_sym: 'BTCUSDT',
  name: 'Bitcoin',
  generated_at: new Date(Date.now() - 2 * 3_600_000).toISOString(),
  expires_at: new Date(Date.now() + 2 * 3_600_000).toISOString(),
  signal: 'BUY',
  confidence_pct: 82,
  weekly_bias: 'BULLISH',
  claude_call:
    "Price is holding above the weekly structure with clean volume. I'd wait for a 4H close inside the entry zone before committing. If it flushes to $97,200, that's the deeper setup. Higher conviction there.",
  support_resistance: [
    { level_type: 'RESISTANCE', strength: 'STRONG', price: 109400, confluence_note: 'Weekly flip zone', sort_order: 1 },
    { level_type: 'RESISTANCE', strength: 'WEAK', price: 105800, confluence_note: null, sort_order: 2 },
    { level_type: 'SUPPORT', strength: 'WEAK', price: 101400, confluence_note: null, sort_order: 3 },
    { level_type: 'SUPPORT', strength: 'STRONG', price: 97200, confluence_note: 'Historical support', sort_order: 4 },
  ],
  indicators: [
    {
      rsi_value: 58.4,
      rsi_status: 'NEUTRAL',
      macd_cross: 'BULLISH',
      price_vs_ema20: 'ABOVE',
      price_vs_ema200: 'ABOVE',
      bb_status: 'NORMAL',
      atr_value: 1840.5,
      volume_status: 'ABOVE_AVG',
    },
  ],
  trade_setups: [
    {
      direction: 'LONG',
      grade: 'A',
      conviction: 'HIGH',
      entry_zone_low: 101200,
      entry_zone_high: 102000,
      stop_tight: 99800,
      stop_safe: 98500,
      risk_pct_tight: 1.4,
      risk_pct_safe: 2.8,
      tp1_price: 105800,
      tp1_rr: 3.8,
      tp2_price: 109400,
      tp2_rr: 7.4,
      tp3_price: 115000,
      tp3_rr: 12.1,
      trigger_note: 'Wait for 4H candle close above $102,000',
      invalidation: '4H close below $99,800',
      setup_note: null,
    },
    {
      direction: 'SHORT',
      grade: 'B',
      conviction: 'MEDIUM',
      entry_zone_low: 109000,
      entry_zone_high: 109500,
      stop_tight: 110200,
      stop_safe: 111000,
      risk_pct_tight: 0.9,
      risk_pct_safe: 1.8,
      tp1_price: 105800,
      tp1_rr: 2.8,
      tp2_price: 101400,
      tp2_rr: 5.9,
      tp3_price: null,
      tp3_rr: null,
      trigger_note: '4H bearish rejection wick inside the red box',
      invalidation: '4H close above $110,200',
      setup_note: 'Counter to daily bias. Half size only.',
    },
  ],
}
