export const BATCH_SIZE = 10  // koin per cron tick (10 koin × 8s = ~80s, aman di bawah Vercel Pro 300s)
export const ANALYSIS_TTL_HOURS = 4
export const COINGECKO_DELAY_MS = 8_000  // 7 req/min safe zone untuk free tier
export const COINGECKO_RATE_LIMIT_WAIT_MS = 30_000

export const SKIP_COINS = new Set([
  'tether', 'usd-coin', 'usds', 'dai', 'paypal-usd', 'global-dollar',
  'ripple-usd', 'usdd', 'bfusd', 'gho', 'usdtb', 'united-stables',
  'usual-usd', 'ethena-usde', 'ylds', 'falcon-finance', 'eutbl',
  'hashnote-usyc', 'blackrock-usd-institutional-digital-liquidity-fund',
  'janus-henderson-anemoy-treasury-fund', 'ondo-us-dollar-yield',
  'superstate-short-duration-us-government-securities-fund-ustb',
  'ousg', 'frax', 'true-usd', 'first-digital-usd', 'binance-usd',
  'paxos-standard', 'gemini-dollar', 'liquity-usd', 'usd-plus',
  'usd1-wlfi', 'apxusd', 'usx',
  'tether-gold', 'pax-gold', 'cache-gold', 'meld-gold', 'kinesis-gold',
  'wrapped-bitcoin', 'wrapped-ether', 'staked-ether', 'wrapped-steth',
  'coinbase-wrapped-staked-eth', 'rocket-pool-eth', 'frax-ether',
  'lido-staked-sol', 'binance-staked-sol', 'wrapped-eeth',
  'figure-heloc', 'gatechain-token', 'hash-2', 'a7a5',
])

export const TV_SYMBOL_MAP: Record<string, string> = {
  'bitcoin':            'BINANCE:BTCUSDT',
  'ethereum':           'BINANCE:ETHUSDT',
  'binancecoin':        'BINANCE:BNBUSDT',
  'solana':             'BINANCE:SOLUSDT',
  'ripple':             'BINANCE:XRPUSDT',
  'cardano':            'BINANCE:ADAUSDT',
  'avalanche-2':        'BINANCE:AVAXUSDT',
  'dogecoin':           'BINANCE:DOGEUSDT',
  'tron':               'BINANCE:TRXUSDT',
  'polkadot':           'BINANCE:DOTUSDT',
  'chainlink':          'BINANCE:LINKUSDT',
  'matic-network':      'BINANCE:MATICUSDT',
  'litecoin':           'BINANCE:LTCUSDT',
  'shiba-inu':          'BINANCE:SHIBUSDT',
  'uniswap':            'BINANCE:UNIUSDT',
  'cosmos':             'BINANCE:ATOMUSDT',
  'stellar':            'BINANCE:XLMUSDT',
  'ethereum-classic':   'BINANCE:ETCUSDT',
  'filecoin':           'BINANCE:FILUSDT',
  'aptos':              'BINANCE:APTUSDT',
  'arbitrum':           'BINANCE:ARBUSDT',
  'optimism':           'BINANCE:OPUSDT',
  'near':               'BINANCE:NEARUSDT',
  'sui':                'BINANCE:SUIUSDT',
  'pepe':               'BINANCE:PEPEUSDT',
  'injective-protocol': 'BINANCE:INJUSDT',
  'aave':               'BINANCE:AAVEUSDT',
  'lido-dao':           'BINANCE:LDOUSDT',
  'render-token':       'BINANCE:RENDERUSDT',
  'stacks':             'BINANCE:STXUSDT',
  'okb':                'OKX:OKBUSDT',
  'cronos':             'BYBIT:CROUSDT',
  'hyperliquid':        'BYBIT:HYPEUSDT',
  'bittensor':          'BINANCE:TAOUSDT',
  'kaspa':              'BYBIT:KASUSDT',
  'monero':             'KRAKEN:XMRUSD',
  'bittorrent':         'BINANCE:BTTCUSDT',
  'internet-computer':  'BINANCE:ICPUSDT',
  'hedera-hashgraph':   'BINANCE:HBARUSDT',
  'vechain':            'BINANCE:VETUSDT',
  'mantle':             'BYBIT:MNTUSDT',
  'the-graph':          'BINANCE:GRTUSDT',
  'theta-token':        'BINANCE:THETAUSDT',
  'algorand':           'BINANCE:ALGOUSDT',
  'fantom':             'BINANCE:FTMUSDT',
  'helium':             'BINANCE:HNTUSDT',
  'flow':               'BINANCE:FLOWUSDT',
  'decentraland':       'BINANCE:MANAUSDT',
  'the-sandbox':        'BINANCE:SANDUSDT',
  'axie-infinity':      'BINANCE:AXSUSDT',
  'chiliz':             'BINANCE:CHZUSDT',
  'curve-dao-token':    'BINANCE:CRVUSDT',
  'compound-governance-token': 'BINANCE:COMPUSDT',
  'maker':              'BINANCE:MKRUSDT',
  'pancakeswap-token':  'BINANCE:CAKEUSDT',
  'thorchain':          'BINANCE:RUNEUSDT',
  'dydx':               'BINANCE:DYDXUSDT',
  'gmx':                'BINANCE:GMXUSDT',
  'immutable-x':        'BINANCE:IMXUSDT',
  'elrond-erd-2':       'BINANCE:EGLDUSDT',
}
